# Generated by Django 6.1.1 on 2026-09-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('General', 'General'), ('Academic', 'Academic'), ('Exam', 'Exam'), ('Event', 'Event'), ('Placement', 'Placement'), ('Holiday', 'Holiday')], default='General', max_length=20)),
                ('notice_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-notice_date', '-created_at'],
            },
        ),
    ]
